export type CountryProps = {
  code: string;
  id: string;
  name: string;
}

export const Countries: Array<CountryProps> = [
  { code: '93', id: 'af', name: 'Afghanistão' },
  { code: '27', id: 'za', name: 'África do Sul' },
  { code: '355', id: 'al', name: 'Albânia' },
  { code: '49', id: 'de', name: 'Alemanha' },
  { code: '376', id: 'ad', name: 'Andora' },
  { code: '244', id: 'ao', name: 'Angola' },
  { code: '1 264', id: 'ai', name: 'Anguilla' },
  { code: '672', id: 'aq', name: 'Antarctica' },
  { code: '1 268', id: 'ag', name: 'Antígua e Barbuda' },
  { code: '54', id: 'ar', name: 'Argentina' },
  { code: '213', id: 'dz', name: 'Argélia' },
  { code: '374', id: 'am', name: 'Arménia' },
  { code: '297', id: 'aw', name: 'Aruba' },
  { code: '966', id: 'sa', name: 'Arábia Saudita' },
  { code: '61', id: 'au', name: 'Austrália' },
  { code: '43', id: 'at', name: 'Áustria' },
  { code: '994', id: 'az', name: 'Azerbaijão' },
  { code: '1 242', id: 'bs', name: 'Bahamas' },
  { code: '973', id: 'bh', name: 'Bahrein' },
  { code: '880', id: 'bd', name: 'Bangladesh' },
  { code: '1 246', id: 'bb', name: 'Barbados' },
  { code: '32', id: 'be', name: 'Bélgica' },
  { code: '501', id: 'bz', name: 'Belize' },
  { code: '229', id: 'bj', name: 'Benim' },
  { code: '1 441', id: 'bm', name: 'Bermuda' },
  { code: '975', id: 'bt', name: 'Butão' },
  { code: '375', id: 'by', name: 'Bielorrússia' },
  { code: '591', id: 'bo', name: 'Bolívia' },
  { code: '387', id: 'ba', name: 'Bósnia e Herzegovina' },
  { code: '267', id: 'bw', name: 'Botswana' },
  { code: '55', id: 'br', name: 'Brasil' },
  { code: '673', id: 'bn', name: 'Brunei' },
  { code: '359', id: 'bg', name: 'Bulgária' },
  { code: '226', id: 'bf', name: 'Burkina Faso' },
  { code: '95', id: 'mm', name: 'Myanmar (Burma)' },
  { code: '257', id: 'bi', name: 'Burundi' },
  { code: '237', id: 'cm', name: 'Camarões' },
  { code: '238', id: 'cv', name: 'Cabo Verde' },
  { code: '855', id: 'kh', name: 'Camboja' },
  { code: '1', id: 'ca', name: 'Canadá' },
  { code: '974', id: 'qa', name: 'Catar' },
  { code: '235', id: 'td', name: 'Chad' },
  { code: '56', id: 'cl', name: 'Chile' },
  { code: '86', id: 'cn', name: 'China' },
  { code: '357', id: 'cy', name: 'Chipre' },
  { code: '61', id: 'cx', name: 'Christmas Island' },
  { code: '65', id: 'sg', name: 'Cingapura' },
  { code: '57', id: 'co', name: 'Colômbia' },
  { code: '269', id: 'km', name: 'Comores' },
  { code: '850', id: 'kp', name: 'Coreia do Norte' },
  { code: '82', id: 'kr', name: 'Coreia do Sul' },
  { code: '225', id: 'ci', name: 'Costa do Marfim' },
  { code: '506', id: 'cr', name: 'Costa Rica' },
  { code: '385', id: 'hr', name: 'Croácia' },
  { code: '53', id: 'cu', name: 'Cuba' },
  { code: '45', id: 'dk', name: 'Dinamarca' },
  { code: '253', id: 'dj', name: 'Djibouti' },
  { code: '1 767', id: 'dm', name: 'Dominica' },
  { code: '20', id: 'eg', name: 'Egito' },
  { code: '503', id: 'sv', name: 'El Salvador' },
  { code: '971', id: 'ae', name: 'Emirados Árabes Uncodeos' },
  { code: '593', id: 'ec', name: 'Equador' },
  { code: '291', id: 'er', name: 'Eritreia' },
  { code: '372', id: 'ee', name: 'Estónia' },
  { code: '34', id: 'es', name: 'Espanha' },
  { code: '251', id: 'et', name: 'Etiópia' },
  { code: '679', id: 'fj', name: 'Fiji' },
  { code: '358', id: 'fi', name: 'Finlândia' },
  { code: '33', id: 'fr', name: 'França' },
  { code: '241', id: 'ga', name: 'Gabão' },
  { code: '220', id: 'gm', name: 'Gâmbia' },
  { code: '995', id: 'ge', name: 'Geórgia' },
  { code: '233', id: 'gh', name: 'Gana' },
  { code: '350', id: 'gi', name: 'Gibraltar' },
  { code: '30', id: 'gr', name: 'Grécia' },
  { code: '299', id: 'gl', name: 'Groelândia' },
  { code: '1 473', id: 'gd', name: 'Granada' },
  { code: '1 671', id: 'gu', name: 'Guam' },
  { code: '502', id: 'gt', name: 'Guatemala' },
  { code: '592', id: 'gy', name: 'Guiana' },
  { code: '224', id: 'gn', name: 'Guiné' },
  { code: '240', id: 'gq', name: 'Guiné Equatorial' },
  { code: '245', id: 'gw', name: 'Guiné-Bissau' },
  { code: '509', id: 'ht', name: 'Haiti' },
  { code: '504', id: 'hn', name: 'Honduras' },
  { code: '852', id: 'hk', name: 'Hong Kong' },
  { code: '36', id: 'hu', name: 'Hungria' },
  { code: '354', id: 'is', name: 'Islândia' },
  { code: '1 345', id: 'ky', name: 'Ilhas Cayman' },
  { code: '61', id: 'cc', name: 'Ilhas Cocos (Keeling)' },
  { code: '44', id: 'im', name: 'Ilha de Man' },
  { code: '682', id: 'ck', name: 'Ilhas Cook' },
  { code: '500', id: 'fk', name: 'Ilhas Falkland (Malvinas)' },
  { code: '298', id: 'fo', name: 'Ilhas Feroé' },
  { code: '1 670', id: 'mp', name: 'Ilhas Mariana do Norte' },
  { code: '692', id: 'mh', name: 'Ilhas Marshall' },
  { code: '870', id: 'pn', name: 'Ilhas Pitcairn' },
  { code: '677', id: 'sb', name: 'Ilhas Salomão' },
  { code: '1 649', id: 'tc', name: 'Ilhas Turcas e Caicos' },
  { code: '1 340', id: 'vi', name: 'Ilhas Virgens Americanas' },
  { code: '1 284', id: 'vg', name: 'Ilhas Virgens Britânicas' },
  { code: '91', id: 'in', name: 'India' },
  { code: '62', id: 'code', name: 'Indonésia' },
  { code: '44', id: 'gb', name: 'Inglaterra (Reino Uncodeo)' },
  { code: '98', id: 'ir', name: 'Irã' },
  { code: '964', id: 'iq', name: 'Iraque' },
  { code: '353', id: 'ie', name: 'Irlanda' },
  { code: '972', id: 'il', name: 'Israel' },
  { code: '39', id: 'it', name: 'Itália' },
  { code: '1 876', id: 'jm', name: 'Jamaica' },
  { code: '81', id: 'jp', name: 'Japão' },
  { code: '962', id: 'jo', name: 'Jordânia' },
  { code: '7', id: 'kz', name: 'Cazaquistão' },
  { code: '254', id: 'ke', name: 'Quénia (Kenya)' },
  { code: '686', id: 'ki', name: 'Kiribati' },
  { code: '965', id: 'kw', name: 'Kuwait' },
  { code: '996', id: 'kg', name: 'Quirguistão' },
  { code: '856', id: 'la', name: 'Laos' },
  { code: '371', id: 'lv', name: 'Letônia' },
  { code: '961', id: 'lb', name: 'Líbano' },
  { code: '266', id: 'ls', name: 'Lesoto' },
  { code: '231', id: 'lr', name: 'Libéria' },
  { code: '218', id: 'ly', name: 'Líbia' },
  { code: '423', id: 'li', name: 'Liechtenstein' },
  { code: '370', id: 'lt', name: 'Lituânia' },
  { code: '352', id: 'lu', name: 'Luxemburgo' },
  { code: '853', id: 'mo', name: 'Macau' },
  { code: '389', id: 'mk', name: 'Macedónia' },
  { code: '261', id: 'mg', name: 'Madagáscar' },
  { code: '265', id: 'mw', name: 'Malawi' },
  { code: '60', id: 'my', name: 'Malásia' },
  { code: '960', id: 'mv', name: 'Maldivas' },
  { code: '223', id: 'ml', name: 'Mali' },
  { code: '356', id: 'mt', name: 'Malta' },
  { code: '222', id: 'mr', name: 'Mauritânia' },
  { code: '230', id: 'mu', name: 'Maurícia' },
  { code: '262', id: 'yt', name: 'Mayotte' },
  { code: '52', id: 'mx', name: 'México' },
  { code: '691', id: 'fm', name: 'Micronésia' },
  { code: '373', id: 'md', name: 'Moldávia' },
  { code: '377', id: 'mc', name: 'Monaco' },
  { code: '976', id: 'mn', name: 'Mongólia' },
  { code: '382', id: 'me', name: 'Montenegro' },
  { code: '1 664', id: 'ms', name: 'Montserrat' },
  { code: '212', id: 'ma', name: 'Marrocos' },
  { code: '258', id: 'mz', name: 'Moçambique' },
  { code: '264', id: 'na', name: 'Namíbia' },
  { code: '674', id: 'nr', name: 'Nauru' },
  { code: '977', id: 'np', name: 'Nepal' },
  { code: '599', id: 'an', name: 'Netherlands Antilles' },
  { code: '687', id: 'nc', name: 'Nova Caledônia' },
  { code: '64', id: 'nz', name: 'Nova Zelândia' },
  { code: '505', id: 'ni', name: 'Nicaragua' },
  { code: '227', id: 'ne', name: 'Níger' },
  { code: '234', id: 'ng', name: 'Nigéria' },
  { code: '683', id: 'nu', name: 'Niue' },
  { code: '47', id: 'no', name: 'Noruega' },
  { code: '968', id: 'om', name: 'Omã' },
  { code: '31', id: 'nl', name: 'Países Baixos' },
  { code: '92', id: 'pk', name: 'Paquistão' },
  { code: '680', id: 'pw', name: 'Palau' },
  { code: '507', id: 'pa', name: 'Panamá' },
  { code: '675', id: 'pg', name: 'Papua-Nova Guiné' },
  { code: '595', id: 'py', name: 'Paraguai' },
  { code: '51', id: 'pe', name: 'Peru' },
  { code: '63', id: 'ph', name: 'Filipinas' },
  { code: '48', id: 'pl', name: 'Polónia' },
  { code: '689', id: 'pf', name: 'Polinésia Francesa' },
  { code: '351', id: 'pt', name: 'Portugal' },
  { code: '1', id: 'pr', name: 'Porto Rico' },
  { code: '242', id: 'cg', name: 'República do Congo' },
  { code: '243', id: 'cd', name: 'Rep. Democrática do Congo' },
  { code: '236', id: 'cf', name: 'República Centro-Africana' },
  { code: '420', id: 'cz', name: 'República Checa' },
  { code: '1 809', id: 'do', name: 'República Dominicana' },
  { code: '40', id: 'ro', name: 'Roménia' },
  { code: '250', id: 'rw', name: 'Ruanda' },
  { code: '7', id: 'ru', name: 'Rússia' },
  { code: '590', id: 'bl', name: 'Saint Barthelemy' },
  { code: '685', id: 'ws', name: 'Samoa' },
  { code: '1 684', id: 'as', name: 'Samoa Americana' },
  { code: '378', id: 'sm', name: 'San Marino' },
  { code: '239', id: 'st', name: 'Sao Tome e Principe' },
  { code: '221', id: 'sn', name: 'Senegal' },
  { code: '381', id: 'rs', name: 'Serbia' },
  { code: '232', id: 'sl', name: 'Serra Leoa' },
  { code: '248', id: 'sc', name: 'Seychelles' },
  { code: '421', id: 'sk', name: 'Slovakia' },
  { code: '386', id: 'si', name: 'Slovenia' },
  { code: '252', id: 'so', name: 'Somalia' },
  { code: '94', id: 'lk', name: 'Sri Lanka' },
  { code: '290', id: 'sh', name: 'Saint Helena' },
  { code: '1 869', id: 'kn', name: 'Saint Kitts and Nevis' },
  { code: '1 758', id: 'lc', name: 'Saint Lucia' },
  { code: '1 599', id: 'mf', name: 'Saint Martin' },
  { code: '508', id: 'pm', name: 'St. Pierre and Miquelon' },
  { code: '1', id: 'vc', name: 'St. Vincent and the Grenadines' },
  { code: '249', id: 'sd', name: 'Sudão' },
  { code: '597', id: 'sr', name: 'Suriname' },
  { code: '268', id: 'sz', name: 'Suazilândia' },
  { code: '46', id: 'se', name: 'Suécia' },
  { code: '41', id: 'ch', name: 'Suiça' },
  { code: '963', id: 'sy', name: 'Syria' },
  { code: '886', id: 'tw', name: 'Taiwan' },
  { code: '992', id: 'tj', name: 'Tajiquistão' },
  { code: '255', id: 'tz', name: 'Tanzânia' },
  { code: '670', id: 'tl', name: 'Timor-Leste' },
  { code: '66', id: 'th', name: 'Tailândia' },
  { code: '228', id: 'tg', name: 'Togo' },
  { code: '690', id: 'tk', name: 'Tokelau' },
  { code: '676', id: 'to', name: 'Tonga' },
  { code: '1 868', id: 'tt', name: 'Trincodead e Tobago' },
  { code: '216', id: 'tn', name: 'Tunísia' },
  { code: '993', id: 'tm', name: 'Turquemenistão' },
  { code: '90', id: 'tr', name: 'Turquia' },
  { code: '688', id: 'tv', name: 'Tuvalu' },
  { code: '256', id: 'ug', name: 'Uganda' },
  { code: '380', id: 'ua', name: 'Ucrânia' },
  { code: '598', id: 'uy', name: 'Uruguai' },
  { code: '1', id: 'us', name: 'Estados Unidos' },
  { code: '998', id: 'uz', name: 'Uzbequistão' },
  { code: '678', id: 'vu', name: 'Vanuatu' },
  { code: '39', id: 'va', name: 'Vaticano' },
  { code: '58', id: 've', name: 'Venezuela' },
  { code: '84', id: 'vn', name: 'Vietnã' },
  { code: '681', id: 'wf', name: 'Wallis e Futuna' },
  { code: '967', id: 'ye', name: 'Iémen' },
  { code: '263', id: 'zw', name: 'Zimbabué' },
  { code: '260', id: 'zm', name: 'Zâmbia' },
];